name: Review Agent CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-minimal.txt
    
    - name: Create required directories
      run: |
        mkdir -p audio_input
        mkdir -p mock_reviews
    
    - name: Run basic tests
      run: |
        python -c "from review_agent.agent import ReviewAgent, ReviewInput; print('Import test passed')"
        python -c "from review_agent.platforms.mock import MockPlatform; print('Platform test passed')"
    
    - name: Run demo (without user input)
      run: |
        python demo.py || true  # Allow to fail gracefully in CI
        python voice_demo_auto.py
    
    - name: Check generated files
      run: |
        ls -la mock_reviews/ || echo "No review files generated"
        ls -la audio_input/ || echo "No audio files"